# Generated by Django 6.0 on 2026-01-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_api', '0002_invoice_amount_paid_invoice_balance_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='laundry_api.staff'),
        ),
    ]
