# Generated by Django 6.0 on 2026-01-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_api', '0003_order_assigned_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_staff',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_ironer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ironing_orders', to='laundry_api.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_washer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washing_orders', to='laundry_api.staff'),
        ),
    ]
